In [2]:
import numpy as np


In [2]:
np.__version__

'2.4.1'

## Create & Read

### !D Array

In [10]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [11]:
arr1.size

6

## 2D Array

In [19]:
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 3)

In [20]:
arr2.size


8

In [21]:
arr2.shape

(2, 4)

## 3D Array

In [25]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[9,2,3],[4,9,6]], [[7,2,7],[0,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 2, 3],
        [4, 9, 6]],

       [[7, 2, 7],
        [0, 5, 6]]])

In [23]:
arr3.ndim

3

In [26]:
arr3.shape


(3, 2, 3)

In [27]:
arr3.size

18

## Create Random Array

In [33]:
randomArr = np.random.rand(3,2,3)

In [34]:
randomArr

array([[[0.57839103, 0.23084313, 0.95757075],
        [0.61620785, 0.9614309 , 0.27170242]],

       [[0.05796391, 0.4656959 , 0.52096382],
        [0.65785148, 0.31579941, 0.92859549]],

       [[0.86915232, 0.38650903, 0.75440812],
        [0.07973368, 0.81976312, 0.17313528]]])

In [66]:
randomArr.dtype

dtype('float64')

In [36]:
randomArr.dtype

dtype('float64')

In [37]:
zeroesArr = np.zeros((3,2,3))
zeroesArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
zeroesArr.dtype

dtype('float64')

In [39]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [40]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 2, 3],
        [4, 9, 6]],

       [[7, 2, 7],
        [0, 5, 6]]])

In [42]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr3[0][0][1]

np.int64(2)

In [49]:
arr3[0][0][2]

np.int64(3)

In [50]:
arr3[0:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 2, 3],
        [4, 9, 6]]])

In [51]:
arr3[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [52]:
arr3[0:3]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 2, 3],
        [4, 9, 6]],

       [[7, 2, 7],
        [0, 5, 6]]])

In [59]:
arr3[0:2][1][0][0] = 11

In [60]:
arr3


array([[[11, 10, 10],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [ 4,  9,  6]],

       [[ 7,  2,  7],
        [ 0,  5,  6]]])

In [62]:
arr3[-2]

array([[11,  2,  3],
       [ 4,  9,  6]])

In [63]:
arr3


array([[[11, 10, 10],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [ 4,  9,  6]],

       [[ 7,  2,  7],
        [ 0,  5,  6]]])

In [64]:
arr3[1][1][1]

np.int64(9)

In [65]:
arr3[1,1,1]

np.int64(9)

## Update & Delete

In [70]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)


In [68]:
a1

array([[[0.57624111, 0.25293128],
        [0.7454569 , 0.48350335],
        [0.55071864, 0.26185065]],

       [[0.84037611, 0.24546508],
        [0.42862014, 0.44146078],
        [0.23485323, 0.4727325 ]]])

In [71]:
a2

array([[[0.21457276, 0.65859665],
        [0.4662102 , 0.87065632],
        [0.0402704 , 0.05287085]],

       [[0.97767179, 0.47602551],
        [0.82580891, 0.290081  ],
        [0.67902521, 0.87703252]]])

## Basic Mathematical Operations

In [72]:
np.add(a1, a2)

array([[[0.67505548, 1.51092561],
        [1.30234127, 1.38755412],
        [0.27796942, 0.13252773]],

       [[1.1675795 , 0.66179977],
        [1.27579517, 1.05181306],
        [0.90799196, 1.81806204]]])

In [73]:
np.subtract(a1, a2)

array([[[ 0.24590995,  0.19373232],
        [ 0.36992087, -0.35375852],
        [ 0.19742863,  0.02678604]],

       [[-0.78776408, -0.29025125],
        [-0.37582265,  0.47165106],
        [-0.45005846,  0.06399699]]])

In [75]:
np.divide(a1, a2)

array([[[2.14604454, 1.29415929],
        [1.7934637 , 0.59368753],
        [5.90257424, 1.50663151]],

       [[0.19424485, 0.39026115],
        [0.54490361, 2.62592882],
        [0.33719919, 1.07296992]]])

In [77]:
np.multiply(a1, a2)

array([[[0.09880705, 0.561341  ],
        [0.38981284, 0.45004034],
        [0.00957223, 0.00421153]],

       [[0.18566741, 0.08843329],
        [0.37160267, 0.220964  ],
        [0.1554742 , 0.82531349]]])

###  Statistical Operations

In [83]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,6)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [79]:
sqrt

np.float64(5.0)

In [80]:
abs

np.int64(2)

In [84]:
power

np.int64(64)

In [85]:
log


np.float64(3.2188758248682006)

In [86]:
mins

np.float64(0.07965688436801643)

In [87]:
maxs

np.float64(0.9776717889108207)

## Update Values

In [88]:
arr3

array([[[11, 10, 10],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [ 4,  9,  6]],

       [[ 7,  2,  7],
        [ 0,  5,  6]]])

In [89]:
arr3[0,0,1] = 12

In [90]:
arr3

array([[[11, 12, 10],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [ 4,  9,  6]],

       [[ 7,  2,  7],
        [ 0,  5,  6]]])

In [91]:
arr3[1,1,2] = 7

In [92]:
arr3

array([[[11, 12, 10],
        [ 4,  5,  6]],

       [[11,  2,  3],
        [ 4,  9,  7]],

       [[ 7,  2,  7],
        [ 0,  5,  6]]])

In [94]:
arr3.sort()  # Lower number to higher
arr3

array([[[10, 11, 12],
        [ 4,  5,  6]],

       [[ 2,  3, 11],
        [ 4,  7,  9]],

       [[ 2,  7,  7],
        [ 0,  5,  6]]])

In [95]:
# Reshape 
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[10, 11, 12],
        [ 4,  5,  6],
        [ 2,  3, 11]],

       [[ 4,  7,  9],
        [ 2,  7,  7],
        [ 0,  5,  6]]])

In [96]:
arr3_reshape.shape


(2, 3, 3)

## Apending & Inserting

In [97]:
zeroes

NameError: name 'zeroes' is not defined

In [99]:
zeroesArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
#  Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
append = np.append(zeroesArr, new_array, axis=0)

NameError: name 'zeroesArr' is not defined

In [5]:
zerosArr

NameError: name 'zerosArr' is not defined

In [6]:
zeroesArr = np.zeros((3,2,3))
zeroesArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
newArr = np.ones((3,2,3))
newArr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
appd = np.append(zeroesArr, newArr, axis=0) #  axis=0 is row and axis=1 is column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
zeroesArr


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
newArr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
insertedArr = np.insert(zeroesArr, 1, newArr, axis=0)
insertedArr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
insertedArr.shape

(6, 2, 3)

## Delete

In [17]:
arr4 =  np.random.rand(3,2,3)
arr4

array([[[0.11132457, 0.40530951, 0.44526317],
        [0.92976649, 0.92354988, 0.79557867]],

       [[0.52653943, 0.17303327, 0.6116901 ],
        [0.41020043, 0.03222107, 0.26839361]],

       [[0.42624999, 0.08541078, 0.94182256],
        [0.31016124, 0.63454576, 0.87353873]]])

In [20]:
# delete the array
arr5 = np.delete(arr4,0, axis=1)

In [21]:
arr5

array([[[0.92976649, 0.92354988, 0.79557867]],

       [[0.41020043, 0.03222107, 0.26839361]],

       [[0.31016124, 0.63454576, 0.87353873]]])

In [22]:
np.save("new array", arr5)

In [23]:
np.load("new array.npy")

array([[[0.92976649, 0.92354988, 0.79557867]],

       [[0.41020043, 0.03222107, 0.26839361]],

       [[0.31016124, 0.63454576, 0.87353873]]])